name: widget_book
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  device_preview: ^1.0.0
  flutter_speed_dial: ^5.0.0+1
  google_fonts: ^2.2.0
  url_launcher: ^6.0.17
  url_launcher_web: ^2.0.5
  awesome_package: ^0.0.1
  transparent_image: ^2.0.0
  
  # tuple: ^2.0.0
  # widget_with_codeview: ^2.0.0-nullsafe
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png" 


flutter:

  uses-material-design: true

  assets:
        - lib/images/
        - lib/widgets_screens/
        - lib/cookbookscreens/

   
         
 
  # fonts:
  #   - family: Raleway
  #     fonts:
  #       - asset: packages/awesome_package/fonts/Raleway-Regular.ttf
  #       - asset: packages/awesome_package/fonts/Raleway-Italic.ttf
  #         style: italic

